<?php

namespace Modules\ExampleModule\Controllers;


use Annotations\Navigation;
use Annotations\SubNavigation;
use Controllers\PublicFrontController;

/**
 * Class ExampleController
 * @package Modules\Example\Controllers
 * @Navigation(text="ExampleModule", position="sidebar")
 */
class IndexController extends PublicFrontController
{
    /**
     * @SubNavigation(text="Example Box")
     */
    public function indexAction(): void
    {
        parent::indexAction(); // TODO: Change the autogenerated stub
    }
}