<?php


namespace Controllers;


use Interfaces\ControllerInterfaces\PublicControllerInterface;

/**
 * Class PublicFrontController
 * @package Controllers
 */
class PublicFrontController extends PublicController implements PublicControllerInterface
{
    /**
     *
     */
    public function indexAction(): void
    {
        parent::indexAction(); // TODO: Change the autogenerated stub
    }
}