<?php

namespace Controllers;


use Interfaces\ControllerInterfaces\PublicControllerInterface;
use Throwable;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Error\SyntaxError;

/**
 * Class PublicFrontController
 * @package Controllers
 */
class PublicFrontController extends PublicController implements PublicControllerInterface
{
    /**
     * @param string $action
     * @throws Throwable
     * @throws LoaderError
     * @throws RuntimeError
     * @throws SyntaxError
     */
    public final function run(string $action)
    {
        parent::run($action); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public function indexAction(): void
    {
        parent::indexAction(); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public final function loginAction(): void
    {
        if($this->getSessionHandler()->isRegistered()){
            $this->getRequestHandler()->doRedirect();
        }
    }
}