<?php


namespace Controllers;

use Interfaces\ControllerInterfaces\RestrictedControllerInterface;

/**
 * Class RestrictedFrontController
 * @package Controllers
 */
class RestrictedFrontController extends RestrictedController implements RestrictedControllerInterface
{
    /**
     *
     */
    public function indexAction(): void
    {
        parent::indexAction(); // TODO: Change the autogenerated stub
    }
}