<?php
////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2019. DW Web-Engineering
// https://www.teamspeak-interface.de
// Developer: Daniel W.
//
// License Informations: This program may only be used in conjunction with a valid license.
// To purchase a valid license please visit the website www.teamspeak-interface.de

namespace Controllers;


use Interfaces\ControllerInterfaces\RestrictedControllerInterface;
use Throwable;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Error\SyntaxError;

/**
 * Class RestrictedController
 * @package Controllers
 */
class RestrictedController extends AbstractBase implements RestrictedControllerInterface
{
    /**
     *
     */
    public function indexAction(): void
    {
        // TODO: Implement indexAction() method.
    }

    /**
     * @param string $action
     * @throws Throwable
     * @throws LoaderError
     * @throws RuntimeError
     * @throws SyntaxError
     */
    public final function run(string $action)
    {
        parent::run($action); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public final function loginOrRegisterAction(): void
    {
        $this->addCss("assets/css/plugins/nprogress.css");
        $this->addCss("assets/css/login.css");

        $this->setJs([
            "assets/js/libs/jquery-3.4.1.min.js",
            "bootstrap/js/bootstrap.min.js",
            "assets/js/libs/lodash.compat.min.js",
            "plugins/uniform/jquery.uniform.min.js",
            "plugins/validation/jquery.validate.min.js",
            "plugins/nprogress/nprogress.js",
            "plugins/cryptojs/aes.js",
            "plugins/cryptojs/md5.js",
            "assets/js/login.js"
        ]);

        $this->addJs("$(document).ready(function(){ \"use strict\"; Login.init(); });", true);
    }

    /**
     *
     */
    public final function loginAction(): void
    {
        $this->addCss("assets/css/plugins/nprogress.css");
        $this->addCss("assets/css/login.css");

        $this->setJs([
            "assets/js/libs/jquery-3.4.1.min.js",
            "bootstrap/js/bootstrap.min.js",
            "assets/js/libs/lodash.compat.min.js",
            "plugins/uniform/jquery.uniform.min.js",
            "plugins/validation/jquery.validate.min.js",
            "plugins/nprogress/nprogress.js",
            "plugins/cryptojs/aes.js",
            "plugins/cryptojs/md5.js",
            "assets/js/login.js"
        ]);

        $this->addJs("$(document).ready(function(){ \"use strict\"; Login.init(); });", true);
    }

    /**
     *
     */
    public final function registerAction(): void
    {
        $this->addCss("assets/css/plugins/nprogress.css");
        $this->addCss("assets/css/login.css");

        $this->setJs([
            "assets/js/libs/jquery-3.4.1.min.js",
            "bootstrap/js/bootstrap.min.js",
            "assets/js/libs/lodash.compat.min.js",
            "plugins/uniform/jquery.uniform.min.js",
            "plugins/validation/jquery.validate.min.js",
            "plugins/nprogress/nprogress.js",
            "plugins/cryptojs/aes.js",
            "plugins/cryptojs/md5.js",
            "assets/js/login.js"
        ]);

        $this->addJs("$(document).ready(function(){ \"use strict\"; Login.init(); });", true);
    }
}